name: Auto Format on Pull Request

on:
  pull_request:
    branches:
      - develop

jobs:
  auto_format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install formatters (black + isort)
      run: pip install black isort

    - name: Format with black
      run: black .

    - name: Sort imports with isort
      run: isort .

    - name: Commit and push if changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git diff --cached --quiet || (git commit -m "Codice formattato :D" && git push)
